# Generated by Django 5.2.6 on 2025-11-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bitki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100, unique=True, verbose_name='Bitki Adı (AI Tahmini)')),
                ('bilimsel_isim', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bilimsel Adı')),
                ('bakim_bilgisi', models.TextField(verbose_name='Genel Bakım İpuçları')),
                ('sulama', models.CharField(max_length=200, verbose_name='Sulama Sıklığı')),
                ('isik', models.CharField(max_length=200, verbose_name='Işık İhtiyacı')),
                ('gorsel', models.ImageField(blank=True, null=True, upload_to='bitki_gorselleri/', verbose_name='Örnek Görsel')),
            ],
        ),
    ]
